### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by Ruslan-B** [ckarcz/CrazyflieDotNet#14]
Hello Chris,

I have minor inquiry - could you please specify this project license ?

Cheers,
Ruslan

**Comment by ckarcz** [comment]
I've decided to use an MIT license. You can do what you wish just provide attribute to this repo somewhere. Though if you make any significant progress or updates please submit a pull request for this repo for myself and others to benefit from. They have already linked from the crazyflie wiki as the C# implementation of their API.

**Comment by Ruslan-B** [comment]
@ckarcz , thank you for fast reply. Perfect choice by the way. I'll inherit same than.  
I'll check in changes soon into my fork. I already got logging working, next will be parameters. 
I used slightly different approach as we need to listen port constantly and handle incoming logging packets meanwhile we still need to send different commands.
I'll send you code review. Thus you can decide how to proceed further.
Cheers, @Ruslan-B
