### ISSUE TITLE
Cannot read any package without sending a package first.

### ISSUE THREAD

**Issue by Ruslan-B** [ckarcz/CrazyflieDotNet#19]
Hello Chris,

Again this not an issue - just a question.
I'm facing right now interesting situation as I cannot read any package without sending a package first.
For example if I sending single command package - drone is getting it and replays with link control  package (four bytes including ack). If package lost or time out happens I'm getting single (n)ack or zero bytes - that is normal.
But logging expecting specific packages as a response, and when sending TOC request package there is no guaranty that I'm going to get a right one (might be (n)ack, might be link control or if other logging is already started might be just a logging data package).
I tried to requery UsbEndpointReader but no matter what it gives timeout, it is just mandatory to send ping package or previous package again. Than I'm getting next package from drone.
This is even in case when drone configured for transition of the logging packages with specified interval.
I tried to use DataReceivedEnabled property  and DataReceivedEnabledChanged event on UsbEndpointReader, with same outcome - you getting only one package after one was sent.
In general this is not an issue as it is possible to resend last package instead of ping, but it consumes drone cpu time as it processes same command over and over again.

Any thoughts?

Cheers,
Ruslan

**Comment by ckarcz** [comment]
Hm. That’s some good stuff you found out.

Looking at the python lib source, it seems that you always get an ACK packet back and the ACK packet data is the response packet:


ackStatus = self.cradio.send_packet(dataOut)
...
…
...
data = ackStatus.data
if (len(data) > 0):
    inPacket = CRTPPacket(data[0], list(data[1:]))
    self.in_queue.put(inPacket)


Looking at the flow of data examples here https://wiki.bitcraze.io/projects:crazyflie:firmware:comm_protocol <https://wiki.bitcraze.io/projects:crazyflie:firmware:comm_protocol>
it seems like the response header is always the same as the request header. We can create the result packet by peeking at the header byte of the ack response data and then creating the correct response packet with the response data.

I think I’m going to try to tackle this ack response payload/data stuff this week and have a working updated example using this. 

Then we can merge in your logging packet classes etc.

**Comment by Ruslan-B** [comment]
Chris, Thank for update,

You probably right and looks like they doing emulation of serial link over radio. 
I just do not want go over radio firmware source code :).
And another point you made here looks like we should "expect" reply. 

Anyway, I've checked in very first logging implementation here:
https://github.com/Ruslan-B/CrazyflieDotNet/commit/154e69c43c79e8f7c2ca006a7a19d46c9c5b8a75
I really tired to reuse your TransferProtocol implementation but end up using only two original enumerations. I tried to be "dry", use a less inheritance as possible and keep packet forming part and packet parsing as close as possible as we need initial packet for parsing.
It is not final yet, but please let me know what do thing about it.

**Comment by ckarcz** [comment]
Thanks I'll take a look. But i want to keep the current packet object models to make this library very user friendly and simple. I'll take your work and incorporate it into the current architecture when I have some time later this week.

Cheers,
Chris :)

**Comment by Ruslan-B** [comment]
Fine with me, my version fits my propose :). I'll keep running my fork as I'm adding parameters support right now. It is quite tricky as their [wiki](https://wiki.bitcraze.io/doc:crazyflie:crtp:param) is completely outdated and does not reflect what they do have in drone firmware. In case you decide to integrate this part as well it will be a way easy for you. I'll keep you posted just in case.

Cheers, Ruslan
